baseURL = "http://shuyanmei.github.io"
relativeURLs = true
canonifyURLs = true
languageCode = "en-us"
title = "SHUYAN"
theme = "hyde"
markdown = "multimarkdown"
# Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[params]
postNavigation = false
highlightjs = true
highlightjsstyle = "dark"
highlightjslanguages = ["python"]
description = "My personal blog"
Copyright = "© 2018 . All Rights Reserved. "
home=""
[params.social]
    linkedin = "shuyanmei"
    github = "shuyanmei"
[permalinks]
    page = "/:title/"
    about = "/:filename/"
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

        